import type { ReactConceptModule } from '../types';

export const REACT_MODULES: ReactConceptModule[] = [
  {
    id: 'overview',
    title: 'React 19 Architecture',
    subtitle: 'The Big Picture',
    description: 'Explore the modern unified pipeline combining Fiber reconciliation, Lane-based prioritization, and the multi-phase execution model.',
    iconName: 'Cpu',
    badge: 'Overview',
    accentColor: '#149eca',
  },
  {
    id: 'rendering',
    title: 'Rendering Pipeline',
    subtitle: 'Trigger → Render → Commit',
    description: 'An interactive simulation of how state updates propagate through Virtual DOM generation, Fiber traversal, and browser paint frames.',
    iconName: 'Activity',
    badge: 'Core Pipeline',
    accentColor: '#10b981',
  },
  {
    id: 'reconciliation',
    title: 'Reconciliation & Diffing',
    subtitle: 'Heuristic O(n) Tree Comparison',
    description: 'Inspect live tree comparison algorithms. Discover how React decides when to reuse, mutate, or destroy DOM nodes based on key & type rules.',
    iconName: 'GitMerge',
    badge: 'Diff Engine',
    accentColor: '#f59e0b',
  },
  {
    id: 'fiber',
    title: 'Fiber Node Explorer',
    subtitle: 'Linked List Work Units',
    description: 'Interactive deep dive into Fiber nodes: child, sibling, and return pointers, alternate double buffering, and side-effect flags.',
    iconName: 'Network',
    badge: 'Data Structure',
    accentColor: '#a855f7',
  },
  {
    id: 'scheduler',
    title: 'Concurrent Scheduler',
    subtitle: 'Time Slicing & Task Yielding',
    description: 'Simulate high-priority user clicks interrupting low-priority background transitions in Reacts cooperative multitasking engine.',
    iconName: 'Clock',
    badge: 'Concurrency',
    accentColor: '#ec4899',
  },
  {
    id: 'lanes',
    title: 'Lanes & Bitmasks',
    subtitle: '31-Bit Priority Engine',
    description: 'Visualize how bitwise OR/AND operations group multiple updates into batches without array allocations or sorting overhead.',
    iconName: 'Layers',
    badge: 'Bitmask Math',
    accentColor: '#3b82f6',
  },
  {
    id: 'commit-phase',
    title: 'Commit Phase & Browser Paint',
    subtitle: 'DOM Mutation & Lifecycle Effects',
    description: 'Step through BeforeMutation, Mutation, and Layout phases before frame compositing and passive useEffect execution.',
    iconName: 'LayoutTemplate',
    badge: 'DOM Pipeline',
    accentColor: '#06b6d4',
  },
];
